### ISSUE TITLE
This library can not use multiple view types more than parent and child

### ISSUE THREAD

**Issue by jyoungrok** [bignerdranch/expandable-recycler-view#108]
https://github.com/bignerdranch/expandable-recycler-view/issues/64

It was already mentioned above and now it's available to override some functions.
However, I think if you make more interfaces or modify current interfaces, developer would implement multiple view types easily

**Comment by paul-turner** [comment]
@jyoungrok Thanks, we are considering how to make this smoother for the developer. I'll use this issue as a tracker for that effort.

**Comment by jyoungrok** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

jyr3357@naver.com 님께 보내신 메일 <Re: [expandable-recycler-view] This library can not use multiple view types more than parent and child (#108)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by charvel02** [comment]
Are you still considering adding the ability to have multiple parent & child view types? This would help me greatly in my current implementation.

**Comment by paul-turner** [comment]
@charvel02 This is on the short list of things we want to do, unfortunately I don't have a good timeline for when that will happen from our side. Contributions are welcome though.

**Comment by julianfalcionelli** [comment]
@paul-turner there is a way to add an header to the recycler view ? Actually i try to add more Types but didn't work.

**Comment by dgreenhalgh** [comment]
@julianfalcionelli We likely won't add something explicitly called a "header", but we're using this story to track the addition of support for multiple view types, one of which you could define to be a header.

**Comment by julianfalcionelli** [comment]
Ok, anyway thanks for all @dgreenhalgh

**Comment by srodenberg** [comment]
Are any changes really needed to support extra view types? When using onCreateParentViewHolder you get the view type which is where you could instantiate different types of views. As long as all of your different view types extend from parent or child this library should work fine correct?

**Comment by paul-turner** [comment]
Would need one or two small changes. 

Currently in the adapter we override `getItemViewType(int position)` to return `TYPE_PARENT` or `TYPE_CHILD` and then our override of `onCreateViewHolder` we use that specific type to call `onCreateParentViewHolder` or `onCreateChildViewHolder`.

In order to support multiple view types properly, we first need to be able to allow the user to return different integers in `getItemViewType` so that `RecyclerView` will pool them correctly. This would then need some logic so that we call the correct `onCreateViewHolder` method according to the viewtype given, which currently depends strongly on just `TYPE_PARENT` or `TYPE_CHILD`.

Hope that helps clear it up!

**Comment by aleksanyan** [comment]
+1

**Comment by eduplus** [comment]
+1

**Comment by aleksanyan** [comment]
@paul-turner I've extended those methods in my adapter. This type of extension allows me to have a header. This also could be used to have a footer. If you do not want to have very general solution for having different custom types in arbitrary position of the list, but only header and footer, I can add my changed and do a pull request. What do you think?

**Comment by eduplus** [comment]
@aleksanyan Your solution would be good solution for something I am working right now, so I would really appreciate your pull request at the very least!

**Comment by aleksanyan** [comment]
@eduplus I've used [this](http://robusttechhouse.com/tutorial-how-to-add-header-to-recyclerview-in-android/) article to have a header. I should help you along with @paul-turner last comment to get it working. I cannot do a pull request at the moment since I will have to merge and generalise my solution with this library.

**Comment by paul-turner** [comment]
Thanks @aleksanyan I think in general it'll be better to have a flexible solution for the library. But your code might be a good stopgap for people to copy into their own projects. Feel free to share as a gist or fork, but for now will be looking for a more general solution in the library when I have the time.

**Comment by DoruAdryan** [comment]
@paul-turner Would you consider having a method like: boolean isParentViewType(), boolean isChildViewType(), which would allow me in the extended Adapter to use, so I can use super in getItemViewType and split the viewType in multiple ones. Hope I explained myself understandably.

**Comment by paul-turner** [comment]
@DoruAdryan Definitely, that's roughly what this issue is representing. Just needs an implementation.

**Comment by iammert** [comment]
I forked and implemented multiple viewType for child view. Also sent [PR](https://github.com/bignerdranch/expandable-recycler-view/pull/182) for this. You can find [sample project](https://github.com/iammert/expandable-recycler-view/tree/master/sampleapp/src/main/java/com/ryanbrooks/expandablerecyclerviewsample/linear/verticalchildviewtype) about how to implement multiple viewtype to child view.

**Comment by Al-Rasel** [comment]
i need multiple parent view type what can i d??
 plz help

**Comment by pasha656** [comment]
It is not good solution, but it work for me. If need add header/footer:

public class ExampleParentViewHolder extends ParentViewHolder {
    private TextView  parentName;

    public ExampleParentViewHolder (View itemView) {
        super(itemView);
        parentName= (TextView)  itemView.findViewById(R.id.parent_name);
    }

    public void bind(ExampleParentItem item) {
        parentName.setText(item.getName());
    }
}


public class ExampleChildViewHolder extends ChildViewHolder{
    private TextView  childName;

    public ExampleChildViewHolder (View itemView) {
        super(itemView);
        childName= (TextView)  itemView.findViewById(R.id.child_name);
    }

    public void bind(ExampleChildItem item) {
        childName.setText(item.getName());
    }
}


public class ExampleFooterViewHolder extends ExampleParentViewHolder {

    public ExampleFooterViewHolder (View itemView) {
        super(itemView);
    }
}


    public class ExampleAdapter extends 
    ExpandableRecyclerAdapter<ExampleParentViewHolder ,  ExampleChildViewHolder > {

    private static final int TYPE_PARENT_FOOTER = 2;

    @Override
    public int getItemViewType(int position) {
        if (position == getItemCount() - 1) { return TYPE_PARENT_FOOTER; }
        return super.getItemViewType(position);
    }

    @Override
    public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup viewGroup, int viewType) {
        if (viewType == TYPE_PARENT_FOOTER) {
            View parent = inflater.inflate(R.layout.item_footer, viewGroup, false);
            return new TaskFooterViewHolder(parent);
        }
        return super.onCreateViewHolder(viewGroup, viewType);
    } }


**R.layout.item_footer** - must contains all view with android:visibility="gone",  what  contains parent, because **ExampleFooterViewHolder extends ExampleParentViewHolder**

**Comment by maohieng** [comment]
I have done with adding some headers by editing your `ExpandableRecyclerAdapter`. I not yet done with adding footer but I think this could be the concept to help improve this library. I like this library.
Here what I do:

- Add a method `getOtherViewTypeCount()` so that user must override it
```
public int getOtherViewTypeCount() {
        return 0;
    }
```

- Modify `getListItem()`, `expandParentListItem()` and `collapseParentListItem()` methods
```
protected Object getListItem(int position) {
        int realPosition = position - getOtherViewTypeCount();
        boolean indexInRange = realPosition >= 0 && realPosition < mItemList.size();
        if (indexInRange) {
            return mItemList.get(realPosition);
        } else {
            return null;
        }
    }

private void expandParentListItem(ParentWrapper parentWrapper, int parentIndex, boolean expansionTriggeredByListItemClick) {
        ...
        mItemList.add(parentIndex - getOtherViewTypeCount() + i + 1, childItemList.get(i));
        ...
}

private void collapseParentListItem(ParentWrapper parentWrapper, int parentIndex, boolean collapseTriggeredByListItemClick) {
        ...
        mItemList.remove(parentIndex - getOtherViewTypeCount() + i + 1);
        ...
}
```

At the app side, must implements `getItemCount()`, `getItemViewType(int position)`, `getOtherViewTypeCount()`, `onCreateViewHolder(ViewGroup viewGroup, int viewType)`, `onBindViewHolder(RecyclerView.ViewHolder holder, int position)` to include their header view(s)...

**Comment by paul-turner** [comment]
With PR #234 this should now be possible. I would love feedback before we make a release!

You can see the 3.0.0 code [here](https://github.com/bignerdranch/expandable-recycler-view/tree/dev-3.0.0)

The [recipe sample](https://github.com/bignerdranch/expandable-recycler-view/blob/dev-3.0.0/sampleapp/src/main/java/com/ryanbrooks/expandablerecyclerviewsample/linear/vertical/RecipeAdapter.java) shows a quick example of using multiple view types

To use the snapshot you will need to add the following to your app's `build.gradle`:

```
compile 'com.bignerdranch.android:expandablerecyclerview:3.0.0-SNAPSHOT'
```

You will also need to add Sonatype's snapshots to your repositories closure in the root `build.gradle`:
 ```gradle
 allprojects {
     repositories {
         maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
     }
 }
 ```

**Comment by DenisMondon** [comment]
With the 3.0.0-SNAPSHOT, I have a ClassCastException:
```
java.lang.ClassCastException: com.radiofrance.radio.franceinter.android.view.holder.StepDepth2ViewHolder cannot be cast to com.bignerdranch.expandablerecyclerview.ParentViewHolder
    at com.bignerdranch.expandablerecyclerview.ExpandableRecyclerAdapter.onBindViewHolder(ExpandableRecyclerAdapter.java:138)
    at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5768)
    at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5801)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5037)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4913)
    at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
    at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
    at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
    at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3260)
    at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3069)
    at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3518)
```

Here is the line in your ExpandableRecyclerAdapter.onBindViewHolder():
`PVH parentViewHolder = (PVH) holder;`

I don't see any problems in my code...

Thanks for your answer :)

P.S. Could you please make mParentItemList protected? thx

**Comment by DenisMondon** [comment]
Ok I understood...
This is because I implementing the getParentItemViewType() method with 2 custom values:
```
@Override
public int getParentItemViewType(int parentPosition) {
    return parentPosition <= 0 ? 5 : 6;
}
```

But in your adapter, you do this:
```
@Override
public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup viewGroup, int viewType) {
    if (isParentViewType(viewType)) { // returns false cause viewType == 5 or 6
        PVH pvh = onCreateParentViewHolder(viewGroup, viewType);
        pvh.setParentListItemExpandCollapseListener(this);
        pvh.mExpandableAdapter = this;
        return pvh;
    } else {
        CVH cvh = onCreateChildViewHolder(viewGroup, viewType);
        cvh.mExpandableAdapter = this;
        return cvh;
    }
}
```
So I was always entering in the "else" condition even for a parent item view.
So I was wondering if the getParentItemViewType() method is useful?

P.S. Could you please make mParentItemList protected? thx

**Comment by paul-turner** [comment]
@DenisMondon Thanks for the feedback!

When overriding`getParentItemViewType()` you will need to override `isParentViewType()` because we are only given the view type when `onCreateViewHolder` is called by the RecyclerView and need to know whether we should be binding a Parent or a Child (but do not have position information to figure it out ourselves). `getParentItemViewType()` is still important because it informs the recycler view what view type you have for that parent item.

I'll look into increasing the visibility of `mParentItemList` I believe we already have an issue for it open.

**Comment by DenisMondon** [comment]
Oh my god, I'm so stupid :D
It works perfectly fine ;)

Could you inform me when mParentItemList is protected?

Thanks a lot ;)
Denis

**Comment by paul-turner** [comment]
No worries, I think this is something that is not clear at first so hopefully the documentation helps when we release it.

Actually I forgot that mParentItemList has a public getter: `getParentItemList()` does that work for your purposes?

**Comment by DenisMondon** [comment]
Thx for your answer but I need to change its value at runtime:
`mParentItemList =  newParentItemList;`

But I can't do this as you know:
`getParentItemList() = parentItemList;`

**Comment by jemmyphan** [comment]
@paul-turner can you fix this link [Recipe Sample](https://github.com/bignerdranch/expandable-recycler-view/blob/dev-3.0.0/sampleapp/src/main/java/com/ryanbrooks/expandablerecyclerviewsample/linear/vertical/RecipeAdapter.java)

**Comment by paul-turner** [comment]
Whoops, fixed the link in the comment. Should now be pointing here:
https://github.com/bignerdranch/expandable-recycler-view/blob/dev-3.0.0/sampleapp/src/main/java/com/bignerdranch/expandablerecyclerviewsample/linear/vertical/RecipeAdapter.java

**Comment by jemmyphan** [comment]
thanks a lot @paul-turner

**Comment by iRYO400** [comment]
@paul-turner 
Hello! 
Can you please show how to bind data for different childs? I mean I dont understand what to do next after this, from your sample code:
```
    @Override
    public void onBindChildViewHolder(IngredientViewHolder ingredientViewHolder, int parentPosition, int childPosition, Object childListItem) {
        Ingredient ingredient = (Ingredient) childListItem;
        ingredientViewHolder.bind(ingredient);
    }
```

Thanks!

**Comment by paul-turner** [comment]
Hi @iRYO400, Good question in our case we didn't have a difference between the two for data binding (just the layout). But if you did you would just set up an if statement within `onBindChildViewHolder` and do the different bind operations you need. This should operate just like multiple view types on a normal RecyclerView.

**Comment by paul-turner** [comment]
Hello, we've released 3.0.0-RC1 with a fix for this issue. 

I would love your feedback with any issues you have with the solution before we make 3.0.0 final. Check out the Pull Request that contains the fix for your issue (should be referenced above), and the [changelog](https://github.com/bignerdranch/expandable-recycler-view/releases/tag/v3.0.0-RC1) for a list of changes that have come with 3.0.0 (there are a lot of them!). 

If you have any issues feel free to re-open this issue with details of what you are seeing.

**Comment by ulusoyca** [comment]
One thing to note here: When you define your own view types as integer constants, don't use `1` as value because it  crashes due to casting PVH or CVH `cannot be cast to com.bignerdranch.expandablerecyclerview.ChildViewHolder` 

Switching it to something else like 5 and 6 fixes.
`  private static final int HEADER = 5;
    private static final int CONTENT = 6;`
`    @Override
    public int getParentViewType(int parentPosition) {
        if (workoutDateList.get(parentPosition).isHeader()) {
            return HEADER;
        } else {
            return CONTENT;
        }
    }`
`    @Override
    public boolean isParentViewType(int viewType) {
        return viewType == HEADER || viewType == CONTENT;
    }`

**Comment by NishantSingh135** [comment]
Hi , I have Edit button in header. When I click on Edit on say i Header, its childviews must show  Deleted icon  which is (Visiblity)Gone by default. How can I achieve this ?? Thanks In advance.

**Comment by NishantSingh135** [comment]
notifyChildItemRemoved(parentPosition, childPosition)  also delete header. Please guide me.
