### ISSUE TITLE
Problem with position of floating action button

### ISSUE THREAD

**Issue by JulienSiems** [bignerdranch/expandable-recycler-view#120]
When I place a floating action button under the recyclerview. It remains in the top left corner no matter what gravity or margin I set. Am I doing something wrong ?

**Comment by paul-turner** [comment]
@JulienSiems could you share your layout xml. This library does not affect layout behaviours, only the adapter and views within the RV.

**Comment by JulienSiems** [comment]
@paul-turner thanks for the answer ! 

my layout containing the recylerview and button looks like this 

```xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_height="match_parent"
    android:layout_width="match_parent"
    android:background="#000000">

    <android.support.design.widget.FloatingActionButton
        android:id="@+id/fab"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="right|bottom"
        android:layout_marginBottom="16dp"
        android:layout_marginRight="16dp"
        android:src="@drawable/ic_add_white_24dp" />

    <android.support.v7.widget.RecyclerView
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/weatherList"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</RelativeLayout>
```

**Comment by paul-turner** [comment]
@JulienSiems Looks like it's because of your use of `RelativeLayout`. `RelativeLayout` does not take `layout_gravity` into account, instead it has parameters like `layout_alignParentBottom` and `layout_alignParentRight` that can achieve what you want, see more about the params [here](https://developer.android.com/reference/android/widget/RelativeLayout.LayoutParams.html).

Alternatively you can use a `FrameLayout` instead of the `RelativeLayout` and your layout will work, since that ViewGroup does follow `layout_gravity`.

**Comment by JulienSiems** [comment]
That solved it! Thank you for taking the time and helping me!
