### ISSUE TITLE
expandParent(position) doesn't work when the parent row has more one child row

### ISSUE THREAD

**Issue by fh127** [bignerdranch/expandable-recycler-view#127]
Hi, all

I am working with this library to show a expandable list, this list is load from request from backend, when I add more one child row in the parent row, I capture this position and load the expandable list and i want to expand this same parent item with expandParent(ParentListItem), but this method doesn't  work, launch the next error:

indexOfBoundException

java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 2(offset:5).state:4

**Comment by paul-turner** [comment]
when you add the child row do you notify the adapter of the change using `notifyChildItemInserted(int parentPosition, int childPosition)` before expanding?

**Comment by fh127** [comment]
No, I don't use notifyChildItemInserted(int parentPosition, int childPosition) because when I delete or add child row, I fill the adapter with new data from backend again. do I need use the notifyChildItemInserted(int parentPosition, int childPosition) when I load all list again?

**Comment by paul-turner** [comment]
How do you fill the adapter with new data? It seems like the problem is that the adapter doesn't know what has changed so the adapters model of the data differs from what you have now set. 

Unfortunately we do not yet support a notifydatasetchanged() for the entire adapter, so you'd have to inform the adapter of the individual changes. The notifyDataSetChanged would allow you to just replace the list and say figure out what has changed (based on stable ID's).
