### ISSUE TITLE
Problem with 'wrap_content' when using multiple views on the same Activity.

### ISSUE THREAD

**Issue by Mauker1** [bignerdranch/expandable-recycler-view#132]
**What I have now**

Say that I have the following xml:

```xml
    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <View 
    	android:id="@+id/some_view"
    	android:layout_width="match_parent"
    	android:layout_height="wrap_content">

            <android.support.v7.widget.RecyclerView
            android:id="@+id/rv_mod_acc"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_below="@id/some_view" />

</RelativeLayout>
```

And that I'm using [this custom LinearLayoutManager](https://github.com/serso/android-linear-layout-manager) to support `wrap_content` on my `RecyclerView`.

Even further, the XML is wrapped around a `android.support.v4.widget.NestedScrollView`.

**The problem**

If I have a small number parents, and I click on one of them to expand, the child gets too small, so if I have a big text to display I'll only have a small window to see it. Like on the pictures below.

<img src='http://imageshack.com/a/img633/4791/EFlHqv.png' width='300' height='400' />

<img src='http://imageshack.com/a/img905/381/p7DXeZ.png' width='300' height='400' />

How to also take the children into account?

**Comment by paul-turner** [comment]
I am not sure how much help I'll be able to be here.

Currently when we add children all we do is add an item into the list and send a notify item inserted (or range inserted). It seems as if this is making the layout manager you use measure out incorrectly?
There is also [this comment](https://github.com/serso/android-linear-layout-manager/blob/master/lib/src/main/java/org/solovyev/android/views/llm/LinearLayoutManager.java#L39) in the layout manager that hints at an inability to add/remove rows with dynamic size.

Unfortunately I feel the problem is with the combination of this adapter and that LLM, however our adapter code is not doing anything special, simply adding in rows and removing them based on user interaction. Which likely puts the bug more on the other side.
