### ISSUE TITLE
Make ParentListItem.isInitiallyExpanded a *default* method that defaults to false

### ISSUE THREAD

**Issue by tir38** [bignerdranch/expandable-recycler-view#137]
I don't want to *have to* override `isInitiallyExpanded()` when I implement `ParentListItem`. It would be nice if the interface had a default implementation that returned false.

**Comment by paul-turner** [comment]
I don't think we can do this with Android unfortunately. Correct me if I'm wrong but interfaces can't have implementations at all right?

**Comment by jingibus** [comment]
A common approach used in the stdlib is to provide a default implementation
of ParentListItem, e.g. SimpleParentListItem, that provides sensible
defaults and maybe a clearer easy path.

**Comment by tir38** [comment]
@paul-turner ahh you are correct!
@jingibus good idea.

**Comment by paul-turner** [comment]
Hello, we've released 3.0.0-RC1 with a fix for this issue. 

I would love your feedback with any issues you have with the solution before we make 3.0.0 final. Check out the Pull Request that contains the fix for your issue (should be referenced above), and the [changelog](https://github.com/bignerdranch/expandable-recycler-view/releases/tag/v3.0.0-RC1) for a list of changes that have come with 3.0.0 (there are a lot of them!). 

If you have any issues feel free to re-open this issue with details of what you are seeing.
