### ISSUE TITLE
rename parentListItems and parentItemsList

### ISSUE THREAD

**Issue by tir38** [bignerdranch/expandable-recycler-view#139]
These two names are confusing and my eyes mix them up all the time. Perhaps `parentItem` and `parentItems` are better? Maybe dropping "item" everywhere is better: `parent` and (`parents` or `parentList`)

**Comment by paul-turner** [comment]
I like this idea of clearing up the names, not sure what to go with yet. :+1:

**Comment by paul-turner** [comment]
Hello, we've released 3.0.0-RC1 with a fix for this issue. 

I would love your feedback with any issues you have with the solution before we make 3.0.0 final. Check out the Pull Request that contains the fix for your issue (should be referenced above), and the [changelog](https://github.com/bignerdranch/expandable-recycler-view/releases/tag/v3.0.0-RC1) for a list of changes that have come with 3.0.0 (there are a lot of them!). 

If you have any issues feel free to re-open this issue with details of what you are seeing.
