### ISSUE TITLE
onBindViewHolder not always called for inserted children

### ISSUE THREAD

**Issue by egor-n** [bignerdranch/expandable-recycler-view#158]
Sometimes when I do `collapseParent` `B` and then `expandParent` `A`, `B`'s children do not get recycled and show up in the `A`'s children.

I tried calling `notifyChildItemRangeChanged` after the `expandParent` and it didn't do anything.

Looking at it with a debugger, `onBindViewHolder` wasn't called for every new child. I don't really know why it happens, but I guess [this](https://github.com/bignerdranch/expandable-recycler-view/blob/89ca7a32ed3647c77de3746a12ebfb6a88d8428e/expandablerecyclerview/src/main/java/com/bignerdranch/expandablerecyclerview/Adapter/ExpandableRecyclerAdapter.java#L1075) doesn't do the job, and `notifyItemRangeInserted` should be called instead.

If I call `notifyItemRangeInserted` instead of `notifyChildItemRangeChanged`, then it works fine.

**Comment by paul-turner** [comment]
Interesting, are these calls happening back to back?

Shouldn't need to call any notify methods because we are calling those for the expand and collapses. I'll take a look into this, any chance one of the samples can be edited to show this bug?

**Comment by egor-n** [comment]
Yes, I call them back to back.

I will try to reproduce the issue this weekend.

**Comment by egor-n** [comment]
Alright, here's the [sample](https://github.com/egor-n/expandable-recycler-view/commit/795470ed21b987bce595e5c9b2faf800ea689a36) and the [video on how to reproduce the issue](https://youtu.be/Gt9X5NfmugA?t=3s).

In the video first I show how it's supposed to work, and then the bug itself. The `99999` seems to be moved out of screen completely.

[This](https://github.com/egor-n/expandable-recycler-view/blob/795470ed21b987bce595e5c9b2faf800ea689a36/sampleapp/src/main/java/com/ryanbrooks/expandablerecyclerviewsample/linear/vertical/VerticalLinearRecyclerViewSampleActivity.java#L72) is what happens when I click on the first parent. I was wrong -- it's not about the `collapseParent` and `expandParent`, it's about the `notifyParentItemRangeRemoved` and `expandParent`. The order doesn't matter.

I don't remove any items from the `mParentItemList`, but the bug remains if I do, so I left it out of the commit.

**Comment by paul-turner** [comment]
@egor-n Thanks for the source code! This may help us get to the bottom of this.

Your last sentence "I don't remove any items from the mParentItemList, but the bug remains if I do, so I left it out of the commit." is one that I'm curious about.

As the sample stands now, the call to `notifyParentItemRangeRemoved` is incorrect because of the fact that no parents have been removed. The notify does not make any modifications to the list, it simply updates the recycler view assuming that those changes have been made. So right now it moves items around from position 1 and 2 out even though those are still present in the adapters data (most likely causing the wrong children to appear when expanding position one, and scrolling it off screen to cause a different item to reload.).

Could you show the case where the bug remains even when the removal of items is happening? I want to see your approach before seeing where I would put said code to better understand the confusion. Hope this isn't too much trouble!

**Comment by egor-n** [comment]
@paul-turner Thank you for your response.

[Here's the code](https://github.com/egor-n/expandable-recycler-view/commit/e517aace22431f82a763ed347fb985229b597db1). The bug is still present with these changes, the `99999` item still appears instead of the `22222`.

**Comment by paul-turner** [comment]
@egor-n found the problem! (At least with this specific case).

`mAdapter.getParentItemList().subList(1, 2)` will return only the second item, because the sublist function is a start and ending index, where the start is inclusive and the end index is exclusive.

This means when we do a clear, we are only deleting item at position 1, so the notify code would need to change to: `mAdapter.notifyParentItemRangeRemoved(1, 2);` or `mAdapter.notifyParentItemRemoved(1);`

Or leave the `parentItemRangeRemoved` as is and change the clear to: `mAdapter.getParentItemList().subList(1, 3)` so that it actually removes the last two.

Let me know if that clears up the issue, or maybe we still have a bug somewhere just need to update the sample a little bit more :)

**Comment by egor-n** [comment]
@paul-turner you are right about the `subList` - it is, in fact, exclusive with the end parameter.

I have [just tried changing it](https://github.com/egor-n/expandable-recycler-view/commit/3530f6d672daa4849005b4121b212ded51f0f2f0) to `.subList(1, 3)` and the problem is still present, though :(

**Comment by paul-turner** [comment]
Ran it again on my computer with the change, everything seems to be ok on my end.

Maybe you ran the old apk by accident? (the link is pointing to the old commit, though I see the new commit with the changes to 1,3)

**Comment by egor-n** [comment]
@paul-turner I've done a clean build and am positive that I am running the latest .apk. The undesired behavior is still present.

I've attached the debugger and stepped through the code. Here's what I see:

![1](https://cloud.githubusercontent.com/assets/378493/12955585/7cdd21b4-d02c-11e5-8a08-7d7a19da4b4e.png)

![2](https://cloud.githubusercontent.com/assets/378493/12955596/869e6d7a-d02c-11e5-8fec-b4aeaf0efc0b.png)

![3](https://cloud.githubusercontent.com/assets/378493/12955599/887e2a2c-d02c-11e5-9e98-2e5677d6788a.png)

The value of `mName` in `Ingredient@4410` is `22222`.

**Comment by egor-n** [comment]
I was able to further isolate this bug. Take a look at [the code here](https://github.com/egor-n/expandable-recycler-view/commit/e36dd459fcfac39ef72a1bd0f466d65a0d061eea), please.

I am not using your library at all at this point. No parent/child item types but the logic remained the same. I do everything manually as would `ExpandableRecyclerAdapter` do.

I am not sure why you can't reproduce this bug. I can say that if the last item does not scroll off the screen, then the bug doesn't appear.

**Comment by paul-turner** [comment]
I see the bug now, turns out you have to scroll down and then scroll back up (I was simply hitting the expand button on the first item).

I've stepped through the code trying to figure out what may be going wrong, based on your last example it feels like it is either a bug with `RecyclerView` or a misuse of the `notify` calls. I'm going to make a simple app that demonstrates the problem and see if I can get other peoples opinions and probably submit a bug report after that.

**Comment by egor-n** [comment]
@paul-turner thanks for spending your time on this! Let me know if I can help you somehow.

**Comment by paul-turner** [comment]
Here is the sample https://github.com/paul-turner/RecyclerViewNotifyTest showing the bug and the bug report here: https://code.google.com/p/android/issues/detail?id=201055&thanks=201055&ts=1455575559

I did see that calling `notifyItemRangeRemoved(1, 4)` resulted in the correct behaviour for my example (instead of saying `notifyItemRangeRemoved(2, 4)` which takes into account the added row). We will see if it is correct or not to shift the indices based on previous data set changes.

**Comment by egor-n** [comment]
Well, I cannot reproduce this bug using the 23.2.0 version.

Too bad it wasn't looked at by a Google dev, who was assigned to the issue. I hope it won't appear again because of that.
