### ISSUE TITLE
When using notifyItemRangeRemoved or notifyItemRangeInserted, affect other layout's offset issue

### ISSUE THREAD

**Issue by albertab880** [bignerdranch/expandable-recycler-view#190]
First of all, thanks for offering this great library. I have an issue when I try to set a LinearLayout(include TextView and ImageView) offsetTopAndBottom at onScrollChange. Just like animation implement by offset the layout, and it work fine. But when I using notifyItemRangeRemoved or notifyItemRangeInserted, it make the layout restore to initial position. I declared recycler view and LinearLayout in main.xml separately. I don't know why the layout can be affected by recycler view.
Please help me to solve this problem. Sorry my English is pretty basic.

**Comment by paul-turner** [comment]
@albertab880 I'm guessing that the layout may be getting repositioned due to the item change. Could I see the `onScrollChange` and/or `offsetTopAndBottom` code that you are seeing be affected? At this point it looks like something that the recyclerView is doing automatically with it's views and not something we can affect with this library.
