### ISSUE TITLE
Click on childitem, get actual item and do something

### ISSUE THREAD

**Issue by hatpick** [bignerdranch/expandable-recycler-view#192]
How to get the actual item (or position) after user taps on the child views?

**Comment by paul-turner** [comment]
Hi @hatpick,

With #171 there is now a snapshot build that should let you access more information from the `ViewHolder`s:
- Added ParentViewHolder methods:
    - `getParentListItem()`
    - `getParentAdapterPosition()`
- Added ChildViewHolder methods:
    - `getChildListItem()`
    - `getParentAdapterPosition()`
    - `getChildAdapterPosition()`

This required changing the package location so bumped up the version to 3.0.0, which means this will probably be a snapshot for a bit as we get more features in for the library.
Instructions on how to get the snapshot are available in the `README` at https://github.com/bignerdranch/expandable-recycler-view/tree/dev

Let me know what you think.

**Comment by YXY1109** [comment]
HI，I am from china.I have a question for you. i want to add clickListener.get curent groupPosition and childPosition in my mainActivity,Lick expandListview.How do that,pleans help me.in my country,only have lick listview.thanks a lot

**Comment by paul-turner** [comment]
@YXY1109 Looks like you need guidance for using a recyclerview instead of a listview? https://www.bignerdranch.com/blog/recyclerview-part-1-fundamentals-for-listview-experts/ and http://stackoverflow.com/questions/24885223/why-doesnt-recyclerview-have-onitemclicklistener-and-how-recyclerview-is-dif

Otherwise if you use the snapshot build of 3.0.0 you can set up a click listener and call the methods above to get positions.
