### ISSUE TITLE
Custom empty view for empty childListItem

### ISSUE THREAD

**Issue by chowaikong** [bignerdranch/expandable-recycler-view#199]
It's possible you guys add a feature that let empty child list display a custom empty view?, Or it's already a workaround to do that?

**Comment by paul-turner** [comment]
Hi @chowaikong I'm not sure that we will be getting around to something like that. The one missing piece for this to be easy as a dev is to have multiple view types allowed. That issue is being tracked here: #108 

Beyond that don't think there is too large a benefit to making this a built in feature. If there is more interest I'll consider reopening this issue.

**Comment by paul-turner** [comment]
With PR #234 we now should have better support for multiple views. I would love feedback before we make a release! Please leave feedback in the original issue tracking this feature #108 

You can see the 3.0.0 code [here](https://github.com/bignerdranch/expandable-recycler-view/tree/dev-3.0.0)

The [recipe sample](https://github.com/bignerdranch/expandable-recycler-view/blob/dev-3.0.0/sampleapp/src/main/java/com/ryanbrooks/expandablerecyclerviewsample/linear/vertical/RecipeAdapter.java) shows a quick example of using multiple view types

To use the snapshot you will need to add the following to your app's `build.gradle`:

```
compile 'com.bignerdranch.android:expandablerecyclerview:3.0.0-SNAPSHOT'
```

You will also need to add Sonatype's snapshots to your repositories closure in the root `build.gradle`:
 ```gradle
 allprojects {
     repositories {
         maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
     }
 }
 ```

Good luck!
