### ISSUE TITLE
flexible align to center

### ISSUE THREAD

**Issue by leonard2014** [bignerdranch/expandable-recycler-view#203]
This is an enhancement suggestion.

For horizontal expandable recyclerview, when its length is shorter than the parent width, can I make it center to the parent horizontal? And when its length is longer than the parent width, change to alight to the start of parent?

You can use the sample app to duplicate this issue, in horizontal linear sample, collapse all parents, then remove parent from end until only parent 0(or 0 and 1, depending on the screen size) is left, there is a big gap to the right of recyclerview.

I need this feature because my app running on tablet, when all parent groups are collapsed (or not all groups, depending on the screen size), the is a gap between the right edge of the recyclerview and the right edge of the screen.  

I tried to use the latest flexbox-layout from google but still could not make it.  Flexbox-layout : https://github.com/google/flexbox-layout

**Comment by paul-turner** [comment]
@leonard2014 Thought about this one for a bit, this would have to be controlled by the `RecyclerView`'s `LayoutManager` since that is what affects the positioning. As a result this would be out of the scope of expandable-recycler-view.  

Another option would be to set `wrap_content` on the RV and have the parent container center it horizontally. That might also work, maybe.

Good luck!
(closing since in all this seems out of scope)
