### ISSUE TITLE
Scrolling of parent view from the expanded view

### ISSUE THREAD

**Issue by vish30** [bignerdranch/expandable-recycler-view#204]
The scrolling works in the parent and child views perfectly, but if the scroll is made on the expanded childview it doesn't scroll the parent view. The scroll stops at the end of the child view and does nothing if more scrolling is done on the childview even though parentview has items left to be scrolled. Is there any option to make the parent scroll when the scroll is done in the childview.

**Comment by paul-turner** [comment]
@vish30 If I am correct here it seems you have nested scrolling going on? 

If that's the case I'm not sure Recyclerview supports being a scrolling parent. You'd want your child views to use [NestedScrollView](https://developer.android.com/reference/android/support/v4/widget/NestedScrollView.html) however [RecyclerView](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.html) only implements [NestedScrollingChild](https://developer.android.com/reference/android/support/v4/view/NestedScrollingChild.html) instead of [NestedScrollingParent](https://developer.android.com/reference/android/support/v4/view/NestedScrollingParent.html) which I _think_ it would need in your situation. This may be something that can be implemented in your own subclass of RV?

This does seem to be out of scope for what expandable-recycler-view is trying to do unfortunately.
