### ISSUE TITLE
Wrong package naming

### ISSUE THREAD

**Issue by YuriDenison** [bignerdranch/expandable-recycler-view#210]
Hello guys,

It really hurts my eyes when I look at 'CamelCase' package names. 
According to any [Java](https://google.github.io/styleguide/javaguide.html#s5.2.1-package-names) [style](http://www.oracle.com/technetwork/java/codeconventions-150003.pdf) [guide](https://source.android.com/source/code-style.html):

> Package names are all lowercase, with consecutive words simply concatenated together (no underscores). For example, com.example.deepspace, not com.example.deepSpace or com.example.deep_space.

Please fix it.

**Comment by YuriDenison** [comment]
https://github.com/bignerdranch/expandable-recycler-view/pull/211
Created

**Comment by paul-turner** [comment]
Hi @YuriDenison Thank you for the PR and sorry for the delay in getting back to you, I think this is fixed in our 3.0.0-Snapshot since I removed the subpackages (see https://github.com/bignerdranch/expandable-recycler-view/compare/dev?expand=1)

Since this is an API breaking change I've been making those changes under the `dev` branch. This has made me realize I should be more clear in the README as far as contributing guidelines. Thank you still for taking a proactive approach to fixing this issue!

**Comment by paul-turner** [comment]
fixed in #171
