### ISSUE TITLE
[request enhancement] getExpandedItemCount 

### ISSUE THREAD

**Issue by visyone** [bignerdranch/expandable-recycler-view#237]
hi, it's possible to extends visibility of this method from private to protected.
I use it for get the exact parent item position when override onParentListItemExpanded.
Thanks a lot.

**Comment by paul-turner** [comment]
Hi @visyone, is there any reason you are overriding `onParentListItemExpanded` instead of using a `ExpandCollapseListener` on the adapter?
Trying to see if it makes sense to hide the visibility of the `ParentListItemExpandCollapseListener`.

I think it would be useful still to raise the visibility of `getExpandedItemCount` to protected too.
