### ISSUE TITLE
How to access parent view holder from child view holder?

### ISSUE THREAD

**Issue by KAPLANDROID** [bignerdranch/expandable-recycler-view#242]
How is this possible? For example I clicked on a button which is in child view holder and i want to set text to a textview which is in parent view holder.

**Comment by XxGoliathusxX** [comment]
So do you know the position of the child?
I use these two methods to get positions. 
The first one only orientates on expanded parents. Just try them a bit. Then you will get the solution you need

   ```
public int getParentPositionOfPosition(int pos){
        int pCount = -1;  
        for(int i = 0; i <= pos; i++){
            Object listItem = getListItem(i);
            if(listItem instanceof ParentWrapper){
                pCount++;
            }
        }
        return pCount;
    }

    public int getChildPositionOfPosition(int pos){
        int cCount = -1;
        for(int i = 0; i <= pos; i++){
            Object listItem = getListItem(i);
            if(listItem instanceof ParentWrapper){
                cCount = -1;
            }else{
                cCount++;
            }
        }
        return cCount;
    }
```

**Comment by KAPLANDROID** [comment]
I tried similar ways like you but I don't want to just get the position index. I want to access view of parent. I check the adapter code there is a variable `mAttachedRecyclerViewPool` which is list of recyclerviews to show on the screen but it has private access.

**Comment by paul-turner** [comment]
It might be best to call `notifyParentItemChanged()` with the parent position you want to update. This will trigger `onBind` to get called again for your parent viewholder and you would be able to update the view. This is better than reaching into the adapter because it handles the case where the parent item might be offscreen and therefore you have no view to display.

Hopefully that helps!
