### ISSUE TITLE
multiple childItems

### ISSUE THREAD

**Issue by GLObus303** [bignerdranch/expandable-recycler-view#246]
![kxeu](https://cloud.githubusercontent.com/assets/12488648/18069967/f3cf9268-6e4a-11e6-88cf-f4336632489b.png)
I am creating multiple CrimeChild(ModuleChildItem) instances to insert various String to my multiple textboxes inside childItem.

Whatsoever, everything works fine except the fact that it creates multiple childItemsView even I am just simply recreating CrimeChild and then attaching it to Crime List.

I understand that this is core function as in your sampleApp the childrens are separated to each own views, but is there somekind of method which would change this ability? I would like to put all child to each List entry as far as I dont know how many entries i will have.

**Comment by paul-turner** [comment]
Correct me if I'm wrong, but it seems you want your parent to only have one child view. If thats the case then you need to have only one item in the `childList`. Since you need variable Strings, you will have your `ModuleChildItem` hold a `List<String>` which you can use to populate your list.

The adapter uses the `childList` in order to determine how many items to show, any extra data should be held in the Child object itself.
