### ISSUE TITLE
Is this possible cooperate with Realm ORM?

### ISSUE THREAD

**Issue by iRYO400** [bignerdranch/expandable-recycler-view#258]
Hi @bignerdranch !
How can I integrate Realm ORM to your recyclerview? In their Sample, they extend from RealmRecyclerView. At this point I dont have any idea what to do

**Comment by paul-turner** [comment]
Hi @iRYO400 
I'm not very familiar with their integration with RecyclerView, but a quick search shows that they also require that you subclass `RealmBasedRecyclerViewAdapter` which is where the two would conflict, since we also require that you subclass our adapter. So out of the box this is not possible, however it is probably pretty simple to write the ORM loading code for your adapter without using [RealmBasedRecyclerViewAdapter](https://github.com/thorbenprimke/realm-recyclerview/blob/master/library/src/main/java/io/realm/RealmBasedRecyclerViewAdapter.java) and therefore allow you to use this library too.

**Comment by Reline** [comment]
@iRYO400 @paul-turner I took a shot at branching this and integrating Realm right on top https://github.com/GPSInsight/realm-expandable-recycler-view/commit/3afac1fe8d6456e21d55d01ccb2f022a7b0328d3. Any feedback is appreciated! 

Working on building a search/filter feature into this as well.

**Comment by dgreenhalgh** [comment]
@Reline Good work! Building in Realm integration is currently outside of the scope of the library, but we'll make sure to keep this in mind in case we get this question in the future.
