### ISSUE TITLE
Resize Recyclerview to show all items

### ISSUE THREAD

**Issue by snijsure** [bignerdranch/expandable-recycler-view#265]
I have been using this excellent library, but for life of me I can figure out following.

My RecyclerView is in NestedScrolleView, 

I have set setNestedScrollingEnabled to false and setHasFixedSize to true for the recyclerview. 

When I add RecyclerView to LinearLayout, I setAutoMeasurable to true for that LinearLayout

However when items are expanded my recycler view doesn't resize to show all items within the adapter. All the elements have attribute layout height `wrap_parent`

What do I have to do to get RecyclerView to resize to show all items upon expand/collapse events?

**Comment by paul-turner** [comment]
Not too familiar with having recyclerviews nested in other scroll views, however it seems like setting `setHasFixedSize` to true goes against with what you are doing. The documentation for `setHasFixedSize` says: 
>RecyclerView's size is not affected by the adapter contents. RecyclerView can still change its size based on other factors (e.g. its parent's size) but this size calculation cannot depend on the size of its children or contents of its adapter (except the number of items in the adapter).
>If your use of RecyclerView falls into this category, set this to true. It will allow RecyclerView to avoid invalidating the whole layout when its adapter contents change.

When you expand a parent, this is adding the child items to the adapter. Because of this attribute being set to true it seems the recyclerview does not try to resize itself and therefore doesn't adapt to the change.

Let me know if I understood you correctly!

**Comment by snijsure** [comment]
Yup that was it as soon as I set setHasFixedSize to false - RecyclerView started to expand / collapse as expected. Thank you so much for "prodding" me to look at the documentation again!

**Comment by swapnilgt** [comment]
Were you able to finally do this ? I am struggling with the same thing...

**Comment by nicparmee** [comment]
@swapnilgt it was 2 years ago? They have propably changed their job, and their lifestyle. By now they are most likely vegan and against computers! Come on man! 

Anyway I can help you what's up?

**Comment by nicparmee** [comment]
@curtismoxam that was two years ago people helped each other a lot more then. Or maybe because it was so long ago they probably don't even have the same job, they probably have a new lifestyle a new car they are probably vegan and don't like computers! Come on man!

Anyway I can help if need be whats up?

**Comment by moudin** [comment]
@nicparmee i need help i recyclerview doesnt show all items there are 41 but it shows 23 :/

**Comment by nicparmee** [comment]
@moudin sorry for the slow reply. 

Can you be a bit more specific does it scroll at all?
But for now, try to put the recycleview into a relativelayout with layout_height as wrap content.
