### ISSUE TITLE
Add new item

### ISSUE THREAD

**Issue by mitko9000** [bignerdranch/expandable-recycler-view#266]
Hello all how I am suppose to add new items with that library can anyone give me any hint because notifydatasetchanged is not working as I can see ?

**Comment by paul-turner** [comment]
Here's an example of doing so in the sample:
https://github.com/bignerdranch/expandable-recycler-view/blob/master/sampleapp/src/main/java/com/ryanbrooks/expandablerecyclerviewsample/linear/horizontal/HorizontalLinearRecyclerViewSampleActivity.java#L193

What you'll need to do is add the item to the List that you passed in to the adapter, then notify the adapter of the change with one of the specific parent/children notify methods that we have available.

**Comment by mitko9000** [comment]
@paul-turner  Hi Paul,
I was trying that but one problem appeared each time I type adapter.notifyParentItemInserted(data.size() - 1); even when adapter change hasn't changed a new parent item appear at the bottom of the list.
All I do is:
loadHeaderData(); -> this will add two elements to the list
adapter.notifyParentItemInserted(data.size() - 1); will update the data passed in

**Comment by paul-turner** [comment]
if `loadHeaderData()` is adding two items then you probably want to say:
```
adapter.notifyParentItemRangeInserted(data.size() - 2, 2);
```
In order to have the adapter update for both (or you can call the single version twice with each index).

Not sure about the issue of calling `notifyParentItemInserted` always adding a parent item at the bottom even if the adapter hasn't changed. Probably should call the notify method if nothing is changed, the behaviour around that is undefined right now (might result in crashes, might add a duplicate item).
