### ISSUE TITLE
Refresh All items while pull to refresh 

### ISSUE THREAD

**Issue by GauravP123** [bignerdranch/expandable-recycler-view#316]
i want to refresh all items as data is changing   at that time  expanded position should remains same . i am calling notifyDataSetChanged(); its not working

**Comment by paul-turner** [comment]
Sorry for the delayed response, the original RecyclerView notify methods are not supported due to api limitations. We've added our own set of `notify...` methods to support data changes, see the docs for a list of all of them.

Take a look at `notifyParentDataSetChanged` [here](https://github.com/bignerdranch/expandable-recycler-view/blob/master/expandablerecyclerview/src/main/java/com/bignerdranch/expandablerecyclerview/ExpandableRecyclerAdapter.java#L829), it should do what you are looking for. You do have more specific notifyParentChanged calls as well.
