### ISSUE TITLE
Variable Child Items

### ISSUE THREAD

**Issue by saadmanfarhad** [bignerdranch/expandable-recycler-view#317]
Hi, I am new to this so I was wondering how to have variable child items in the parent items. Like Parent Item 1 can have 2 child, Parent 2 can have 5 child. And how add them dynamically from a database for example ? An example will really helpful. Thanks !

**Comment by paul-turner** [comment]
@saadmanfarhad Sorry for the late reply.

In order to have variable child items you will just need to set up your child lists with different number of objects. See the samples we have for the app in:
- https://github.com/bignerdranch/expandable-recycler-view/blob/master/sampleapp/src/main/java/com/bignerdranch/expandablerecyclerviewsample/linear/vertical/VerticalLinearRecyclerViewSampleActivity.java
- https://github.com/bignerdranch/expandable-recycler-view/blob/master/sampleapp/src/main/java/com/bignerdranch/expandablerecyclerviewsample/linear/horizontal/HorizontalLinearRecyclerViewSampleActivity.java

Unfortunately I do not have the time to show dynamic loading etc. You will need to adapt your code from there. None of that is specific to working with this library once you have loaded the data.
