### ISSUE TITLE
Sticky headers

### ISSUE THREAD

**Issue by RedEagle07** [bignerdranch/expandable-recycler-view#53]
Is there a way to make the headers pinned as in Instgram? I tried to use SuperSLim Library along expandable-recycler-view however it didn't not work

**Comment by paul-turner** [comment]
@RedEagle07 I'm not familiar with the SuperSLiM library, but the two should be able to coexist since this library focus on adapter changes, while the other uses custom layout managers to give sticky headers.

Beyond that I do not have much experience with sticky headers in a RecyclerView so will not be able to help (and is not a focus of this library at this time).

**Comment by i-schuetz** [comment]
@RedEagle07 Did you get it working?
