### ISSUE TITLE
Way to prevent multiple activities being created when double tapping the childview?

### ISSUE THREAD

**Issue by ThatKawaiiGuy** [bignerdranch/expandable-recycler-view#61]
Is there a way to prevent duplicate activities being made when the childview is double tapped? I fixed it in other recyclerviews by adding a boolean canStart thats set false when an Activity is created, and then set true in the onResume of the activity with the recyclerview. But since the listener is assigned in the adapter, this method is not possible. Does anyone have any suggestions?

**Comment by ThatKawaiiGuy** [comment]
Well, it appears I have fixed my own issue. 

I have created a boolean ```canStart = true``` in the adapter
And then had made my OnClickListener like so:
```
childViewHolder.dataText.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if(canStart) {
                    // Whatever you want to do and not have run twice due to double tap
                }
            }
}
```

and then added a setCanStart method to the adapter class:
```
public void setCanStart(boolean can){
        canStart = can;
}
```

And then in the fragment's or activity's onResume() where the adapter is assigned to the recyclerview, I added the following method:
```
@Override
public void onResume() {
    super.onResume();
    mExpandableAdapter.setCanStart(true);
}
```

I suggest you add this and my previous solution to the README.

**Comment by paul-turner** [comment]
@ThatKawaiiGuy I think this has to do with the click listener not debouncing, I recommend using [ButterKnife](https://github.com/JakeWharton/butterknife) which already has a debouncing click listener that it uses internally: [DebouncingOnClickListener](https://github.com/JakeWharton/butterknife/blob/f94577d17c34bd58eba22a5bd71d09bbf36dc428/butterknife/src/main/java/butterknife/internal/DebouncingOnClickListener.java)

Since it is a common problem not unique to this library I'm going to leave it out of the readme, hope it helps. If not glad you found a solution.

**Comment by ThatKawaiiGuy** [comment]
I meant to add the solution for the onClickListener to the readme. Might not be something someone would come up with instantly.

**Comment by nathtek136** [comment]
I am facing same issue. how can solve it? I tried both way but could solve it, can you explain more details
