### ISSUE TITLE
Missing methods

### ISSUE THREAD

**Issue by XxGoliathusxX** [bignerdranch/expandable-recycler-view#96]
Hey guys,
I really like your lib but ive got some questions. After following your example (works well btw) i noticed some methods are missing:
Here is what i got:

        recyclerView = (RecyclerView) findViewById(R.id.expListView);
        recyclerView.setLayoutManager(new LinearLayoutManager(TestActivity.this));
        ExpandableAdapter expAdapter = new ExpandableAdapter(this, generateCrimes());
         

   <//Is missing

        mCrimeExpandableAdapter.setCustomParentAnimationViewId
        (R.id.parent_list_item_expand_arrow);
        mCrimeExpandableAdapter.setParentClickableViewAnimationDefaultDuration();
        mCrimeExpandableAdapter.setParentAndIconExpandOnClick(true);

//>

        recyclerView.setAdapter(expAdapter);

Furthermore i ask myself if its possible to add drag and swipe behaviour to the list with Touchhelper. Has someone handled that already. I used Touchhelper for my non-expandable recyclerview where it works well.
Thx for help!

**Comment by paul-turner** [comment]
Hi @XxGoliathusxX,
Correct those methods have been removed in 2.0.0+ of the library, we needed to simplify the adapter in order to get some better/simpler functionality in. It is still possible to do the same animation and custom click target in your ParentViewHolder and we have a couple samples to show this.

[VerticalParentViewHolder](https://github.com/bignerdranch/expandable-recycler-view/blob/master/app/src/main/java/com/ryanbrooks/expandablerecyclerviewsample/linear/vertical/VerticalParentViewHolder.java) shows just the animation functionality.
[HorizontalParentViewHolder](https://github.com/bignerdranch/expandable-recycler-view/blob/master/app/src/main/java/com/ryanbrooks/expandablerecyclerviewsample/linear/horizontal/HorizontalParentViewHolder.java) shows both the animation and setting the touch target for expansion to be just the arrow icon.

Hopefully those two get you on track if not let me know how I can help.

For drag and swipe behaviour, I don't think anything in this library should get in the way, so you should be able to implement as you did before. However I have not implemented drag/swipe behaviour myself yet. Have you run into problems or are just in the planning stage of implementing it?

**Comment by XxGoliathusxX** [comment]
Thank you for your fast answer.
Next I'll check HorizontalParentViewHolder like you said. After that I'll try to implement the drag and swipe. Let's see how far I get.

**Comment by XxGoliathusxX** [comment]
Ok the animation and "OnlyExpandOrCollapseIfClickedOnButton" works and runs smooth. GJ :D

**Comment by zajnbovv** [comment]
Can I ask you something?
How can I remove expand or collapse animation?
I wanna fixed List Height and there is quited anoise when I collapse or expand if the height is shorter.
If can, could you give me some advise for that? I have tried to use Thread but didn't works.
Thanks

**Comment by dgreenhalgh** [comment]
@zajnbovv You may be able to write your own ItemAnimator that doesn't animate, but as of right now we stick with the default animation.

**Comment by zajnbovv** [comment]
@dgreenhalgh Thank for your rep. 
Could you tell me how can I change the default animation? All I see now just custom expand image, Did I missed something here?

**Comment by dgreenhalgh** [comment]
@zajnbovv Your best bet would be to look into [RecyclerView.ItemAnimator](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.ItemAnimator.html). Improving animation/animation support is something on our roadmap, although I don't have any new information on that right now.

We'd love some help in improving it if you end up implementing a solution!
