### ISSUE TITLE
Feedback Adapter Expand

### ISSUE THREAD

**Issue by XxGoliathusxX** [bignerdranch/expandable-recycler-view#97]
Hey,
for my drag and swipe behaviour I have to know in the ADAPTER class which parent-items are expanded. So i can count the position of the moved/swiped item and whether its a parent or child - item. Have you an idea?

**Comment by paul-turner** [comment]
Right now there isn't a very simple way, but I think the following should be possible:
given the position that you have you can access the `mItemList` variable in your adapter and get the item at that position. From there if it is an `instanceof` `ParentWrapper` then you have a Parent Item, if not it is a child. If it is a `ParentWrapper` you should be able to get the `ParentItem` it is wrapping which will help you add/remove it with our notify methods.

Hopefully that helps. I'll be thinking of ways to simplify this interaction, welcome any ideas.

**Comment by XxGoliathusxX** [comment]
Hey @paul-turner,
here is a quick example what the problem is:
Example: Every parent has one child.
P0
P1
When I swipe P1 and none is expanded, the returned position is 1.
Now if P0 is expanded:
P0
C1
P1
When I swipe C1 the returned position is 1 too.
When I swipe P1 instead the position is 2.

So i have to know which parents are expanded to count to the position of the swiped item.

**Comment by paul-turner** [comment]
I think my previous answer still holds the most value to you.

[mItemList](https://github.com/bignerdranch/expandable-recycler-view/blob/master/expandablerecyclerview/src/main/java/com/bignerdranch/expandablerecyclerview/Adapter/ExpandableRecyclerAdapter.java#L48) in the expandable adapter holds all the items represented in the RV (A combination of `ParentWrappers` that hold a reference to your `ParentItem` and the bare Child `Object`). 

In example your it would hold:
```
0: ParentWrapper holding P0
1: ParentWrapper holding P1
```
when you expand P0 it will then be updated to hold
```
0: ParentWrapper holding P0
1: Child Object C1
2: ParentWrapper holding P1
```

So given the index if you pull out the object from `mItemList` you will be getting the parent or child that was swiped on. From there a couple of `instanceof` checks should get you the information you need about what parent or child object it is (probably by comparing the P0 or C1 object to what you have in your list of ParentItems.

Hopefully that clears up my previous answer, I think it will be easier than keeping track of the individual states yourself. Also the ParentWrapper objects in that list hold the `isExpanded` state you mention, so that might be what you want in all as well (just make sure that you note the children are also in that list when traversing, not all objects are ParentWrappers all the time in `mItemList`)

**Comment by XxGoliathusxX** [comment]
I solved it. Can be closed.

**Comment by Anu07** [comment]
Hi Can You help me with the solution that you found for above scenario? I am not having viewtypes for my parent and child
